/******************************************************************************/
/***               Generated by IBExpert 23/12/2011 00:40:02                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE TBESTADO (
    EST_COD    SMALLINT NOT NULL,
    EST_NOME   VARCHAR(100),
    EST_SIGLA  VARCHAR(2),
    EST_SIAFI  INTEGER
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TBESTADO ADD CONSTRAINT PK_TBESTADO PRIMARY KEY (EST_COD);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/

Insert Into TBESTADO values (11, 'RONDÔNIA', 'RO', null);
Insert Into TBESTADO values (12, 'ACRE', 'AC', null);
Insert Into TBESTADO values (13, 'AMAZONAS', 'AM', null);
Insert Into TBESTADO values (14, 'RORAIMA', 'RR', null);
Insert Into TBESTADO values (15, 'PARÁ', 'PA', null);
Insert Into TBESTADO values (16, 'AMAPÁ', 'AP', null);
Insert Into TBESTADO values (17, 'TOCANTINS', 'TO', null);
Insert Into TBESTADO values (21, 'MARANHÃO', 'MA', null);
Insert Into TBESTADO values (22, 'PIAUÍ', 'PI', null);
Insert Into TBESTADO values (23, 'CEARÁ', 'CE', null);
Insert Into TBESTADO values (24, 'RIO GRANDE DO NORTE', 'RN', null);
Insert Into TBESTADO values (25, 'PARAÍBA', 'PB', null);
Insert Into TBESTADO values (26, 'PERNAMBUCO', 'PE', null);
Insert Into TBESTADO values (27, 'ALAGOAS', 'AL', null);
Insert Into TBESTADO values (28, 'SERGIPE', 'SE', null);
Insert Into TBESTADO values (29, 'BAHIA', 'BA', null);
Insert Into TBESTADO values (31, 'MINAS GERAIS', 'MG', null);
Insert Into TBESTADO values (32, 'ESPÍRITO SANTO', 'ES', null);
Insert Into TBESTADO values (33, 'RIO DE JANEIRO', 'RJ', null);
Insert Into TBESTADO values (35, 'SÃO PAULO', 'SP', null);
Insert Into TBESTADO values (41, 'PARANÁ', 'PR', null);
Insert Into TBESTADO values (42, 'SANTA CATARINA', 'SC', null);
Insert Into TBESTADO values (43, 'RIO GRANDE DO SUL', 'RS', null);
Insert Into TBESTADO values (50, 'MATO GROSSO DO SUL', 'MS', null);
Insert Into TBESTADO values (51, 'MATO GROSSO', 'MT', null);
Insert Into TBESTADO values (52, 'GOIÁS', 'GO', null);
Insert Into TBESTADO values (53, 'DISTRITO FEDERAL', 'DF', null);
