/******************************************************************************/
/***               Generated by IBExpert 23/12/2011 23:24:03                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_BAIRRO_ID;

CREATE TABLE TBBAIRRO (
    BAI_COD   INTEGER NOT NULL,
    BAI_NOME  VARCHAR(100),
    CID_COD   INTEGER,
    DIS_COD   SMALLINT
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TBBAIRRO ADD CONSTRAINT PK_TBBAIRRO PRIMARY KEY (BAI_COD);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE TBBAIRRO ADD CONSTRAINT FK_TBBAIRRO_CID FOREIGN KEY (CID_COD) REFERENCES TBCIDADE (CID_COD) ON UPDATE CASCADE;
ALTER TABLE TBBAIRRO ADD CONSTRAINT FK_TBBAIRRO_DIS FOREIGN KEY (DIS_COD) REFERENCES TBDISTRITO (DIS_COD) ON UPDATE CASCADE;


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: TG_BAIRRO_COD */
CREATE OR ALTER TRIGGER TG_BAIRRO_COD FOR TBBAIRRO
ACTIVE BEFORE INSERT POSITION 0
As
Begin
  If (New.Bai_cod Is Null) Then
    New.Bai_cod = Gen_id(Gen_bairro_id,1);
End
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/

