/******************************************************************************/
/***               Generated by IBExpert 24/12/2011 21:50:51                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE TBPAIS (
    PAIS_ID    VARCHAR(5) NOT NULL,
    PAIS_NOME  VARCHAR(150)
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TBPAIS ADD CONSTRAINT PK_TBPAIS PRIMARY KEY (PAIS_ID);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/

alter table TBEMPRESA
add constraint FK_TBEMPRESA_PAIS
foreign key (PAIS_ID)
references TBPAIS(PAIS_ID)
on update CASCADE;

Insert Into TBPAIS values ('00132', 'AFEGANISTAO');
Insert Into TBPAIS values ('00175', 'ALBANIA, REPUBLICA  DA');
Insert Into TBPAIS values ('00230', 'ALEMANHA');
Insert Into TBPAIS values ('00310', 'BURKINA FASO');
Insert Into TBPAIS values ('00370', 'ANDORRA');
Insert Into TBPAIS values ('00400', 'ANGOLA');
Insert Into TBPAIS values ('00418', 'ANGUILLA');
Insert Into TBPAIS values ('00434', 'ANTIGUA E BARBUDA');
Insert Into TBPAIS values ('00477', 'ANTILHAS HOLANDESAS');
Insert Into TBPAIS values ('00531', 'ARABIA SAUDITA');
Insert Into TBPAIS values ('00590', 'ARGELIA');
Insert Into TBPAIS values ('00639', 'ARGENTINA');
Insert Into TBPAIS values ('00647', 'ARMENIA, REPUBLICA DA');
Insert Into TBPAIS values ('00655', 'ARUBA');
Insert Into TBPAIS values ('00698', 'AUSTRALIA');
Insert Into TBPAIS values ('00728', 'AUSTRIA');
Insert Into TBPAIS values ('00736', 'AZERBAIJAO, REPUBLICA DO');
Insert Into TBPAIS values ('00779', 'BAHAMAS, ILHAS');
Insert Into TBPAIS values ('00809', 'BAHREIN, ILHAS');
Insert Into TBPAIS values ('00817', 'BANGLADESH');
Insert Into TBPAIS values ('00833', 'BARBADOS');
Insert Into TBPAIS values ('00850', 'BELARUS, REPUBLICA DA');
Insert Into TBPAIS values ('00876', 'BELGICA');
Insert Into TBPAIS values ('00884', 'BELIZE');
Insert Into TBPAIS values ('00906', 'BERMUDAS');
Insert Into TBPAIS values ('00930', 'MIANMAR (BIRMANIA)');
Insert Into TBPAIS values ('00973', 'BOLIVIA, ESTADO PLURINACIONAL DA');
Insert Into TBPAIS values ('00981', 'BOSNIA-HERZEGOVINA (REPUBLICA DA)');
Insert Into TBPAIS values ('01015', 'BOTSUANA');
Insert Into TBPAIS values ('01058', 'BRASIL');
Insert Into TBPAIS values ('01082', 'BRUNEI');
Insert Into TBPAIS values ('01112', 'BULGARIA, REPUBLICA DA');
Insert Into TBPAIS values ('01155', 'BURUNDI');
Insert Into TBPAIS values ('01198', 'BUTAO');
Insert Into TBPAIS values ('01279', 'CABO VERDE, REPUBLICA DE');
Insert Into TBPAIS values ('01376', 'CAYMAN, ILHAS');
Insert Into TBPAIS values ('01414', 'CAMBOJA');
Insert Into TBPAIS values ('01457', 'CAMAROES');
Insert Into TBPAIS values ('01490', 'CANADA');
Insert Into TBPAIS values ('01504', 'GUERNSEY, ILHA DO CANAL (INCLUI ALDERNEY E SARK)');
Insert Into TBPAIS values ('01508', 'JERSEY, ILHA DO CANAL');
Insert Into TBPAIS values ('01511', 'CANARIAS, ILHAS');
Insert Into TBPAIS values ('01538', 'CAZAQUISTAO, REPUBLICA DO');
Insert Into TBPAIS values ('01546', 'CATAR');
Insert Into TBPAIS values ('01589', 'CHILE');
Insert Into TBPAIS values ('01600', 'CHINA, REPUBLICA POPULAR');
Insert Into TBPAIS values ('01619', 'FORMOSA (TAIWAN)');
Insert Into TBPAIS values ('01635', 'CHIPRE');
Insert Into TBPAIS values ('01651', 'COCOS(KEELING),ILHAS');
Insert Into TBPAIS values ('01694', 'COLOMBIA');
Insert Into TBPAIS values ('01732', 'COMORES, ILHAS');
Insert Into TBPAIS values ('01775', 'CONGO');
Insert Into TBPAIS values ('01830', 'COOK, ILHAS');
Insert Into TBPAIS values ('01872', 'COREIA (DO NORTE), REP.POP.DEMOCRATICA');
Insert Into TBPAIS values ('01902', 'COREIA (DO SUL), REPUBLICA DA');
Insert Into TBPAIS values ('01937', 'COSTA DO MARFIM');
Insert Into TBPAIS values ('01953', 'CROACIA (REPUBLICA DA)');
Insert Into TBPAIS values ('01961', 'COSTA RICA');
Insert Into TBPAIS values ('01988', 'COVEITE');
Insert Into TBPAIS values ('01996', 'CUBA');
Insert Into TBPAIS values ('02291', 'BENIN');
Insert Into TBPAIS values ('02321', 'DINAMARCA');
Insert Into TBPAIS values ('02356', 'DOMINICA,ILHA');
Insert Into TBPAIS values ('02399', 'EQUADOR');
Insert Into TBPAIS values ('02402', 'EGITO');
Insert Into TBPAIS values ('02437', 'ERITREIA');
Insert Into TBPAIS values ('02445', 'EMIRADOS ARABES UNIDOS');
Insert Into TBPAIS values ('02453', 'ESPANHA');
Insert Into TBPAIS values ('02461', 'ESLOVENIA, REPUBLICA DA');
Insert Into TBPAIS values ('02470', 'ESLOVACA, REPUBLICA');
Insert Into TBPAIS values ('02496', 'ESTADOS UNIDOS');
Insert Into TBPAIS values ('02518', 'ESTONIA, REPUBLICA DA');
Insert Into TBPAIS values ('02534', 'ETIOPIA');
Insert Into TBPAIS values ('02550', 'FALKLAND (ILHAS MALVINAS)');
Insert Into TBPAIS values ('02593', 'FEROE, ILHAS');
Insert Into TBPAIS values ('02674', 'FILIPINAS');
Insert Into TBPAIS values ('02712', 'FINLANDIA');
Insert Into TBPAIS values ('02755', 'FRANCA');
Insert Into TBPAIS values ('02810', 'GABAO');
Insert Into TBPAIS values ('02852', 'GAMBIA');
Insert Into TBPAIS values ('02895', 'GANA');
Insert Into TBPAIS values ('02917', 'GEORGIA, REPUBLICA DA');
Insert Into TBPAIS values ('02933', 'GIBRALTAR');
Insert Into TBPAIS values ('02976', 'GRANADA');
Insert Into TBPAIS values ('03018', 'GRECIA');
Insert Into TBPAIS values ('03050', 'GROENLANDIA');
Insert Into TBPAIS values ('03093', 'GUADALUPE');
Insert Into TBPAIS values ('03131', 'GUAM');
Insert Into TBPAIS values ('03174', 'GUATEMALA');
Insert Into TBPAIS values ('03255', 'GUIANA FRANCESA');
Insert Into TBPAIS values ('03298', 'GUINE');
Insert Into TBPAIS values ('03310', 'GUINE-EQUATORIAL');
Insert Into TBPAIS values ('03344', 'GUINE-BISSAU');
Insert Into TBPAIS values ('03379', 'GUIANA');
Insert Into TBPAIS values ('03417', 'HAITI');
Insert Into TBPAIS values ('03450', 'HONDURAS');
Insert Into TBPAIS values ('03514', 'HONG KONG');
Insert Into TBPAIS values ('03557', 'HUNGRIA, REPUBLICA DA');
Insert Into TBPAIS values ('03573', 'IEMEN');
Insert Into TBPAIS values ('03595', 'MAN, ILHA DE');
Insert Into TBPAIS values ('03611', 'INDIA');
Insert Into TBPAIS values ('03654', 'INDONESIA');
Insert Into TBPAIS values ('03697', 'IRAQUE');
Insert Into TBPAIS values ('03727', 'IRA, REPUBLICA ISLAMICA DO');
Insert Into TBPAIS values ('03751', 'IRLANDA');
Insert Into TBPAIS values ('03794', 'ISLANDIA');
Insert Into TBPAIS values ('03832', 'ISRAEL');
Insert Into TBPAIS values ('03867', 'ITALIA');
Insert Into TBPAIS values ('03913', 'JAMAICA');
Insert Into TBPAIS values ('03964', 'JOHNSTON, ILHAS');
Insert Into TBPAIS values ('03999', 'JAPAO');
Insert Into TBPAIS values ('04030', 'JORDANIA');
Insert Into TBPAIS values ('04111', 'KIRIBATI');
Insert Into TBPAIS values ('04200', 'LAOS, REP.POP.DEMOCR.DO');
Insert Into TBPAIS values ('04235', 'LEBUAN,ILHAS');
Insert Into TBPAIS values ('04260', 'LESOTO');
Insert Into TBPAIS values ('04278', 'LETONIA, REPUBLICA DA');
Insert Into TBPAIS values ('04316', 'LIBANO');
Insert Into TBPAIS values ('04340', 'LIBERIA');
Insert Into TBPAIS values ('04383', 'LIBIA');
Insert Into TBPAIS values ('04405', 'LIECHTENSTEIN');
Insert Into TBPAIS values ('04421', 'LITUANIA, REPUBLICA DA');
Insert Into TBPAIS values ('04456', 'LUXEMBURGO');
Insert Into TBPAIS values ('04472', 'MACAU');
Insert Into TBPAIS values ('04499', 'MACEDONIA, ANT.REP.IUGOSLAVA');
Insert Into TBPAIS values ('04502', 'MADAGASCAR');
Insert Into TBPAIS values ('04525', 'MADEIRA, ILHA DA');
Insert Into TBPAIS values ('04553', 'MALASIA');
Insert Into TBPAIS values ('04588', 'MALAVI');
Insert Into TBPAIS values ('04618', 'MALDIVAS');
Insert Into TBPAIS values ('04642', 'MALI');
Insert Into TBPAIS values ('04677', 'MALTA');
Insert Into TBPAIS values ('04723', 'MARIANAS DO NORTE');
Insert Into TBPAIS values ('04740', 'MARROCOS');
Insert Into TBPAIS values ('04766', 'MARSHALL,ILHAS');
Insert Into TBPAIS values ('04774', 'MARTINICA');
Insert Into TBPAIS values ('04855', 'MAURICIO');
Insert Into TBPAIS values ('04880', 'MAURITANIA');
Insert Into TBPAIS values ('04885', 'MAYOTTE (ILHAS FRANCESAS)');
Insert Into TBPAIS values ('04901', 'MIDWAY, ILHAS');
Insert Into TBPAIS values ('04936', 'MEXICO');
Insert Into TBPAIS values ('04944', 'MOLDAVIA, REPUBLICA DA');
Insert Into TBPAIS values ('04952', 'MONACO');
Insert Into TBPAIS values ('04979', 'MONGOLIA');
Insert Into TBPAIS values ('04985', 'MONTENEGRO');
Insert Into TBPAIS values ('04995', 'MICRONESIA');
Insert Into TBPAIS values ('05010', 'MONTSERRAT,ILHAS');
Insert Into TBPAIS values ('05053', 'MOCAMBIQUE');
Insert Into TBPAIS values ('05070', 'NAMIBIA');
Insert Into TBPAIS values ('05088', 'NAURU');
Insert Into TBPAIS values ('05118', 'CHRISTMAS,ILHA (NAVIDAD)');
Insert Into TBPAIS values ('05177', 'NEPAL');
Insert Into TBPAIS values ('05215', 'NICARAGUA');
Insert Into TBPAIS values ('05258', 'NIGER');
Insert Into TBPAIS values ('05282', 'NIGERIA');
Insert Into TBPAIS values ('05312', 'NIUE,ILHA');
Insert Into TBPAIS values ('05355', 'NORFOLK,ILHA');
Insert Into TBPAIS values ('05380', 'NORUEGA');
Insert Into TBPAIS values ('05428', 'NOVA CALEDONIA');
Insert Into TBPAIS values ('05452', 'PAPUA NOVA GUINE');
Insert Into TBPAIS values ('05487', 'NOVA ZELANDIA');
Insert Into TBPAIS values ('05517', 'VANUATU');
Insert Into TBPAIS values ('05568', 'OMA');
Insert Into TBPAIS values ('05665', 'PACIFICO,ILHAS DO (POSSESSAO DOS EUA)');
Insert Into TBPAIS values ('05738', 'PAISES BAIXOS (HOLANDA)');
Insert Into TBPAIS values ('05754', 'PALAU');
Insert Into TBPAIS values ('05762', 'PAQUISTAO');
Insert Into TBPAIS values ('05800', 'PANAMA');
Insert Into TBPAIS values ('05860', 'PARAGUAI');
Insert Into TBPAIS values ('05894', 'PERU');
Insert Into TBPAIS values ('05932', 'PITCAIRN,ILHA');
Insert Into TBPAIS values ('05991', 'POLINESIA FRANCESA');
Insert Into TBPAIS values ('06033', 'POLONIA, REPUBLICA DA');
Insert Into TBPAIS values ('06076', 'PORTUGAL');
Insert Into TBPAIS values ('06114', 'PORTO RICO');
Insert Into TBPAIS values ('06238', 'QUENIA');
Insert Into TBPAIS values ('06254', 'QUIRGUIZ, REPUBLICA');
Insert Into TBPAIS values ('06289', 'REINO UNIDO');
Insert Into TBPAIS values ('06408', 'REPUBLICA CENTRO-AFRICANA');
Insert Into TBPAIS values ('06475', 'REPUBLICA DOMINICANA');
Insert Into TBPAIS values ('06602', 'REUNIAO, ILHA');
Insert Into TBPAIS values ('06653', 'ZIMBABUE');
Insert Into TBPAIS values ('06700', 'ROMENIA');
Insert Into TBPAIS values ('06750', 'RUANDA');
Insert Into TBPAIS values ('06769', 'RUSSIA, FEDERACAO DA');
Insert Into TBPAIS values ('06777', 'SALOMAO, ILHAS');
Insert Into TBPAIS values ('06858', 'SAARA OCIDENTAL');
Insert Into TBPAIS values ('06874', 'EL SALVADOR');
Insert Into TBPAIS values ('06904', 'SAMOA');
Insert Into TBPAIS values ('06912', 'SAMOA AMERICANA');
Insert Into TBPAIS values ('06955', 'SAO CRISTOVAO E NEVES,ILHAS');
Insert Into TBPAIS values ('06971', 'SAN MARINO');
Insert Into TBPAIS values ('07005', 'SAO PEDRO E MIQUELON');
Insert Into TBPAIS values ('07056', 'SAO VICENTE E GRANADINAS');
Insert Into TBPAIS values ('07102', 'SANTA HELENA');
Insert Into TBPAIS values ('07153', 'SANTA LUCIA');
Insert Into TBPAIS values ('07200', 'SAO TOME E PRINCIPE, ILHAS');
Insert Into TBPAIS values ('07285', 'SENEGAL');
Insert Into TBPAIS values ('07315', 'SEYCHELLES');
Insert Into TBPAIS values ('07358', 'SERRA LEOA');
Insert Into TBPAIS values ('07370', 'SERVIA');
Insert Into TBPAIS values ('07412', 'CINGAPURA');
Insert Into TBPAIS values ('07447', 'SIRIA, REPUBLICA ARABE DA');
Insert Into TBPAIS values ('07480', 'SOMALIA');
Insert Into TBPAIS values ('07501', 'SRI LANKA');
Insert Into TBPAIS values ('07544', 'SUAZILANDIA');
Insert Into TBPAIS values ('07560', 'AFRICA DO SUL');
Insert Into TBPAIS values ('07595', 'SUDAO');
Insert Into TBPAIS values ('07641', 'SUECIA');
Insert Into TBPAIS values ('07676', 'SUICA');
Insert Into TBPAIS values ('07706', 'SURINAME');
Insert Into TBPAIS values ('07722', 'TADJIQUISTAO, REPUBLICA DO');
Insert Into TBPAIS values ('07765', 'TAILANDIA');
Insert Into TBPAIS values ('07803', 'TANZANIA, REP.UNIDA DA');
Insert Into TBPAIS values ('07820', 'TERRITORIO BRIT.OC.INDICO');
Insert Into TBPAIS values ('07838', 'DJIBUTI');
Insert Into TBPAIS values ('07889', 'CHADE');
Insert Into TBPAIS values ('07919', 'TCHECA, REPUBLICA');
Insert Into TBPAIS values ('07951', 'TIMOR LESTE');
Insert Into TBPAIS values ('08001', 'TOGO');
Insert Into TBPAIS values ('08052', 'TOQUELAU,ILHAS');
Insert Into TBPAIS values ('08109', 'TONGA');
Insert Into TBPAIS values ('08150', 'TRINIDAD E TOBAGO');
Insert Into TBPAIS values ('08206', 'TUNISIA');
Insert Into TBPAIS values ('08230', 'TURCAS E CAICOS,ILHAS');
Insert Into TBPAIS values ('08249', 'TURCOMENISTAO, REPUBLICA DO');
Insert Into TBPAIS values ('08273', 'TURQUIA');
Insert Into TBPAIS values ('08281', 'TUVALU');
Insert Into TBPAIS values ('08311', 'UCRANIA');
Insert Into TBPAIS values ('08338', 'UGANDA');
Insert Into TBPAIS values ('08451', 'URUGUAI');
Insert Into TBPAIS values ('08478', 'UZBEQUISTAO, REPUBLICA DO');
Insert Into TBPAIS values ('08486', 'VATICANO, EST.DA CIDADE DO');
Insert Into TBPAIS values ('08508', 'VENEZUELA');
Insert Into TBPAIS values ('08583', 'VIETNA');
Insert Into TBPAIS values ('08630', 'VIRGENS,ILHAS (BRITANICAS)');
Insert Into TBPAIS values ('08664', 'VIRGENS,ILHAS (E.U.A.)');
Insert Into TBPAIS values ('08702', 'FIJI');
Insert Into TBPAIS values ('08737', 'WAKE, ILHA');
Insert Into TBPAIS values ('08885', 'CONGO, REPUBLICA DEMOCRATICA DO');
Insert Into TBPAIS values ('08907', 'ZAMBIA');
