/******************************************************************************/
/***               Generated by IBExpert 29/12/2011 07:58:53                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE TBFORNECEDOR_GRUPO (
    GRF_COD        SMALLINT NOT NULL,
    GRF_DESCRICAO  VARCHAR(50)
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TBFORNECEDOR_GRUPO ADD CONSTRAINT PK_TBFORNECEDOR_GRUPO PRIMARY KEY (GRF_COD);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/

INSERT INTO TBFORNECEDOR_GRUPO (GRF_COD, GRF_DESCRICAO)
                        VALUES (0, '* Indefinido');
INSERT INTO TBFORNECEDOR_GRUPO (GRF_COD, GRF_DESCRICAO)
                        VALUES (1, 'Produtos / Serviços');
INSERT INTO TBFORNECEDOR_GRUPO (GRF_COD, GRF_DESCRICAO)
                        VALUES (2, 'Transportadora');

COMMIT WORK;

ALTER TABLE TBFORNECEDOR
    ADD GRF_COD SMALLINT;
    
alter table TBFORNECEDOR
add constraint FK_TBFORNECEDOR_GRUPO
foreign key (GRF_COD)
references TBFORNECEDOR_GRUPO(GRF_COD)
on update CASCADE;

Update TBFORNECEDOR Set GRF_COD = 0 Where GRF_COD is null;
     