/******************************************************************************/
/***               Generated by IBExpert 23/12/2011 00:14:48                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_TIPO_LOGRADOURO_ID;

CREATE TABLE TBTIPO_LOGRADOURO (
    TLG_COD        SMALLINT NOT NULL,
    TLG_DESCRICAO  VARCHAR(50),
    TLG_SIGLA      VARCHAR(10)
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TBTIPO_LOGRADOURO ADD CONSTRAINT PK_TBTIPO_LOGRADOURO PRIMARY KEY (TLG_COD);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: TG_TIPO_LOGRADOURO_COD */
CREATE OR ALTER TRIGGER TG_TIPO_LOGRADOURO_COD FOR TBTIPO_LOGRADOURO
ACTIVE BEFORE INSERT POSITION 0
As
Begin
  If (New.Tlg_cod Is Null) Then
    New.Tlg_cod = Gen_id(Gen_tipo_logradouro_id,1);
End
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


INSERT INTO TBTIPO_LOGRADOURO (TLG_COD, TLG_DESCRICAO, TLG_SIGLA)
                       VALUES (0, '* Indefinido', '');
INSERT INTO TBTIPO_LOGRADOURO (TLG_COD, TLG_DESCRICAO, TLG_SIGLA)
                       VALUES (1, 'ACESSO', 'AC');
INSERT INTO TBTIPO_LOGRADOURO (TLG_COD, TLG_DESCRICAO, TLG_SIGLA)
                       VALUES (2, 'AVENIDA', 'AV.');
INSERT INTO TBTIPO_LOGRADOURO (TLG_COD, TLG_DESCRICAO, TLG_SIGLA)
                       VALUES (3, 'RUA', 'RUA');
INSERT INTO TBTIPO_LOGRADOURO (TLG_COD, TLG_DESCRICAO, TLG_SIGLA)
                       VALUES (4, 'RODOVIA', 'ROD.');
INSERT INTO TBTIPO_LOGRADOURO (TLG_COD, TLG_DESCRICAO, TLG_SIGLA)
                       VALUES (5, 'RUELA', 'RLA.');
INSERT INTO TBTIPO_LOGRADOURO (TLG_COD, TLG_DESCRICAO, TLG_SIGLA)
                       VALUES (6, 'RIO', 'RIO');
INSERT INTO TBTIPO_LOGRADOURO (TLG_COD, TLG_DESCRICAO, TLG_SIGLA)
                       VALUES (7, 'SÍTIO', NULL);
INSERT INTO TBTIPO_LOGRADOURO (TLG_COD, TLG_DESCRICAO, TLG_SIGLA)
                       VALUES (8, 'QUADRA', NULL);
INSERT INTO TBTIPO_LOGRADOURO (TLG_COD, TLG_DESCRICAO, TLG_SIGLA)
                       VALUES (9, 'SUBQUADRA', NULL);
INSERT INTO TBTIPO_LOGRADOURO (TLG_COD, TLG_DESCRICAO, TLG_SIGLA)
                       VALUES (10, 'TRAVESSA', 'TV.');
INSERT INTO TBTIPO_LOGRADOURO (TLG_COD, TLG_DESCRICAO, TLG_SIGLA)
                       VALUES (11, 'VALE', NULL);
INSERT INTO TBTIPO_LOGRADOURO (TLG_COD, TLG_DESCRICAO, TLG_SIGLA)
                       VALUES (12, 'VIA', 'VIA');
INSERT INTO TBTIPO_LOGRADOURO (TLG_COD, TLG_DESCRICAO, TLG_SIGLA)
                       VALUES (13, 'VIADUTO', NULL);
INSERT INTO TBTIPO_LOGRADOURO (TLG_COD, TLG_DESCRICAO, TLG_SIGLA)
                       VALUES (14, 'VIELA', NULL);
INSERT INTO TBTIPO_LOGRADOURO (TLG_COD, TLG_DESCRICAO, TLG_SIGLA)
                       VALUES (15, 'VILA', 'VILA');
INSERT INTO TBTIPO_LOGRADOURO (TLG_COD, TLG_DESCRICAO, TLG_SIGLA)
                       VALUES (16, 'VIAGEM', NULL);

COMMIT WORK;