/******************************************************************************/
/***               Generated by IBExpert 24/12/2011 01:13:29                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_LOGRADOURO_ID;

CREATE TABLE TBLOGRADOURO (
    LOG_COD   INTEGER NOT NULL,
    LOG_NOME  VARCHAR(250),
    TLG_COD   SMALLINT,
    CID_COD   INTEGER
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TBLOGRADOURO ADD CONSTRAINT PK_TBLOGRADOURO PRIMARY KEY (LOG_COD);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE TBLOGRADOURO ADD CONSTRAINT FK_TBLOGRADOURO_CID FOREIGN KEY (CID_COD) REFERENCES TBCIDADE (CID_COD) ON UPDATE CASCADE;
ALTER TABLE TBLOGRADOURO ADD CONSTRAINT FK_TBLOGRADOURO_TIP FOREIGN KEY (TLG_COD) REFERENCES TBTIPO_LOGRADOURO (TLG_COD) ON UPDATE CASCADE;


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: TG_LOGRADOURO_COD */
CREATE OR ALTER TRIGGER TG_LOGRADOURO_COD FOR TBLOGRADOURO
ACTIVE BEFORE INSERT POSITION 0
As
Begin
  If (New.Log_cod Is Null) Then
    New.Log_cod = Gen_id(Gen_logradouro_id,1);
End
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
