CREATE DOMAIN DMN_TEXTO AS
BLOB SUB_TYPE 1 SEGMENT SIZE 80;

CREATE DOMAIN DMN_VCHAR_01 AS
VARCHAR(1);

CREATE DOMAIN DMN_VCHAR_02 AS
VARCHAR(2);

CREATE DOMAIN DMN_VCHAR_03 AS
VARCHAR(3);

CREATE SEQUENCE GEN_GRUPOPRODUTO_COD;

CREATE TRIGGER TG_GRUPOPRODUTO_COD FOR TBGRUPOPROD
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.COD IS NULL) THEN
    NEW.COD = GEN_ID(GEN_GRUPOPRODUTO_COD,1);
END;

/******************************************************************************/
/***               Generated by IBExpert 29/12/2011 13:53:02                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;

/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/

CREATE GENERATOR GEN_SECAOPRODUTO_ID;

CREATE TABLE TBSECAOPROD (
    SCP_COD        SMALLINT NOT NULL,
    SCP_DESCRICAO  VARCHAR(50)
);

/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TBSECAOPROD ADD CONSTRAINT PK_TBSECAOPROD PRIMARY KEY (SCP_COD);

/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/

SET TERM ^ ;

/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/

/* Trigger: TG_SECAOPRODUTO_COD */
CREATE OR ALTER TRIGGER TG_SECAOPRODUTO_COD FOR TBSECAOPROD
ACTIVE BEFORE INSERT POSITION 0
As
Begin
  If (New.Scp_cod Is Null) Then
    New.Scp_cod = Gen_id(Gen_secaoproduto_id,1);
End
^

SET TERM ; ^

/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/

/******************************************************************************/
/***               Generated by IBExpert 29/12/2011 14:14:47                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;

/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/

CREATE GENERATOR GEN_UNIDADEPRODUTO_ID;

CREATE TABLE TBUNIDADEPROD (
    UNP_COD        SMALLINT NOT NULL,
    UNP_DESCRICAO  VARCHAR(50),
    UNP_SIGLA      VARCHAR(5)
);

/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TBUNIDADEPROD ADD CONSTRAINT PK_TBUNIDADEPROD PRIMARY KEY (UNP_COD);

/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/

SET TERM ^ ;

/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/

/* Trigger: TG_UNIDADEPRODUTO_COD */
CREATE OR ALTER TRIGGER TG_UNIDADEPRODUTO_COD FOR TBUNIDADEPROD
ACTIVE BEFORE INSERT POSITION 0
As
Begin
  If (New.Unp_cod Is Null) Then
    New.Unp_cod = Gen_id(Gen_unidadeproduto_id,1);
End
^

SET TERM ; ^

/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/

/******************************************************************************/
/***               Generated by IBExpert 03/01/2012 21:18:02                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE TBTRIBUTACAO_TIPO (
    TPT_COD        DMN_VCHAR_02 NOT NULL /* DMN_VCHAR_02 = VARCHAR(2) */,
    TPT_DESCRICAO  VARCHAR(100),
    TPT_SIGLA      VARCHAR(10)
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TBTRIBUTACAO_TIPO ADD CONSTRAINT PK_TBTRIBUTACAO_TIPO PRIMARY KEY (TPT_COD);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/

/******************************************************************************/
/***               Generated by IBExpert 03/01/2012 21:18:14                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE TBORIGEMPROD (
    ORP_COD        DMN_VCHAR_01 NOT NULL /* DMN_VCHAR_01 = VARCHAR(1) */,
    ORP_DESCRICAO  VARCHAR(50),
    ORP_SIGLA      VARCHAR(5)
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TBORIGEMPROD ADD CONSTRAINT PK_TBORIGEMPROD PRIMARY KEY (ORP_COD);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/

INSERT INTO TBORIGEMPROD (ORP_COD, ORP_DESCRICAO, ORP_SIGLA)
                  VALUES ('0', 'Nacional', NULL);
INSERT INTO TBORIGEMPROD (ORP_COD, ORP_DESCRICAO, ORP_SIGLA)
                  VALUES ('1', 'Estrangeira - Importação direta', NULL);
INSERT INTO TBORIGEMPROD (ORP_COD, ORP_DESCRICAO, ORP_SIGLA)
                  VALUES ('2', 'Estrangeira - Adquirida no mercado interno', NULL);

COMMIT WORK;

INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES ('00', 'Tributada integralmente', NULL);
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES ('10', 'Tributada e com cobrança de ICMS por substituição tributária', NULL);
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES ('20', 'Com redução de base de cálculo', NULL);
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES ('30', 'Isenta ou não tributada e com cobrança de ICMS por substituição tributária', NULL);
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES ('40', 'Isenta', NULL);
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES ('41', 'Não tributada', NULL);
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES ('50', 'Suspensão', NULL);
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES ('51', 'Diferimento', NULL);
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES ('60', 'ICMS cobrado anteriormente por substituição tributária', NULL);
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES ('70', 'Com redução de base de cálculo e cobrança de ICMS por substituição tributária', NULL);
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES ('90', 'Outras', NULL);

COMMIT WORK;

create view vw_origem_produto ( Orp_cod, Orp_descricao, Orp_descricao_full, Orp_sigla )
as
Select
    o.Orp_cod
  , o.Orp_descricao
  , o.Orp_cod || ' - ' || o.Orp_descricao as Orp_descricao_full
  , o.Orp_sigla
from TBORIGEMPROD o;

create view vw_tipo_tributacao ( Tpt_cod, Tpt_descricao, Tpt_descricao_full, Tpt_sigla )
as
Select
    t.Tpt_cod
  , t.Tpt_descricao
  , t.Tpt_cod || ' - ' || t.Tpt_descricao as Tpt_descricao_full
  , t.Tpt_sigla
from TBTRIBUTACAO_TIPO t;

create view vw_tipo_aliquota ( Codigo, Descricao )
as
Select First 1
    0 as Codigo
  , 'ICMS' as Descricao
from TBORIGEMPROD

union

Select First 1
    1 as Codigo
  , 'ISS' as Descricao
from TBORIGEMPROD;
