CREATE DOMAIN DMN_TEXTO AS
BLOB SUB_TYPE 1 SEGMENT SIZE 80;

CREATE DOMAIN DMN_VCHAR_01 AS
VARCHAR(1);

CREATE DOMAIN DMN_VCHAR_02 AS
VARCHAR(2);

CREATE DOMAIN DMN_VCHAR_03 AS
VARCHAR(3);

CREATE SEQUENCE GEN_GRUPOPRODUTO_COD;

CREATE TRIGGER TG_GRUPOPRODUTO_COD FOR TBGRUPOPROD
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.COD IS NULL) THEN
    NEW.COD = GEN_ID(GEN_GRUPOPRODUTO_COD,1);
END;

/******************************************************************************/
/***               Generated by IBExpert 29/12/2011 13:53:02                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;

/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/

CREATE GENERATOR GEN_SECAOPRODUTO_ID;

CREATE TABLE TBSECAOPROD (
    SCP_COD        SMALLINT NOT NULL,
    SCP_DESCRICAO  VARCHAR(50)
);

/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TBSECAOPROD ADD CONSTRAINT PK_TBSECAOPROD PRIMARY KEY (SCP_COD);

/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/

SET TERM ^ ;

/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/

/* Trigger: TG_SECAOPRODUTO_COD */
CREATE OR ALTER TRIGGER TG_SECAOPRODUTO_COD FOR TBSECAOPROD
ACTIVE BEFORE INSERT POSITION 0
As
Begin
  If (New.Scp_cod Is Null) Then
    New.Scp_cod = Gen_id(Gen_secaoproduto_id,1);
End
^

SET TERM ; ^

/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/

/******************************************************************************/
/***               Generated by IBExpert 29/12/2011 14:14:47                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;

/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/

CREATE GENERATOR GEN_UNIDADEPRODUTO_ID;

CREATE TABLE TBUNIDADEPROD (
    UNP_COD        SMALLINT NOT NULL,
    UNP_DESCRICAO  VARCHAR(50),
    UNP_SIGLA      VARCHAR(5)
);

/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TBUNIDADEPROD ADD CONSTRAINT PK_TBUNIDADEPROD PRIMARY KEY (UNP_COD);

/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/

SET TERM ^ ;

/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/

/* Trigger: TG_UNIDADEPRODUTO_COD */
CREATE OR ALTER TRIGGER TG_UNIDADEPRODUTO_COD FOR TBUNIDADEPROD
ACTIVE BEFORE INSERT POSITION 0
As
Begin
  If (New.Unp_cod Is Null) Then
    New.Unp_cod = Gen_id(Gen_unidadeproduto_id,1);
End
^

SET TERM ; ^

/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/

