CREATE DOMAIN DMN_TEXTO AS
BLOB SUB_TYPE 1 SEGMENT SIZE 80;

CREATE TABLE TBORIGEMPROD (
    ORP_COD        SMALLINT NOT NULL,
    ORP_DESCRICAO  VARCHAR(50),
    ORP_SIGLA      VARCHAR(5)
);

ALTER TABLE TBORIGEMPROD ADD CONSTRAINT PK_TBORIGEMPROD PRIMARY KEY (ORP_COD);

INSERT INTO TBORIGEMPROD (ORP_COD, ORP_DESCRICAO, ORP_SIGLA)
                       VALUES (0, 'Nacional', '0');
INSERT INTO TBORIGEMPROD (ORP_COD, ORP_DESCRICAO, ORP_SIGLA)
                       VALUES (1, 'Estrangeira - Importação direta', '1');
INSERT INTO TBORIGEMPROD (ORP_COD, ORP_DESCRICAO, ORP_SIGLA)
                       VALUES (2, 'Estrangeira - Adquirida no mercado interno', '2');

COMMIT WORK;

CREATE TABLE TBTRIBUTACAO_TIPO (
    TPT_COD        SMALLINT NOT NULL,
    TPT_DESCRICAO  VARCHAR(100),
    TPT_SIGLA      VARCHAR(10)
);

ALTER TABLE TBTRIBUTACAO_TIPO ADD CONSTRAINT PK_TBTRIBUTACAO_TIPO PRIMARY KEY (TPT_COD);

INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES (0, 'Tributada integralmente', '00');
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES (1, 'Tributada e com cobrança de ICMS por substituição tributária', '10');
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES (2, 'Com redução de base de cálculo', '20');
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES (3, 'Isenta ou não tributada e com cobrança de ICMS por substituição tributária', '30');
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES (4, 'Isenta', '40');
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES (5, 'Não tributada', '41');
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES (6, 'Suspensão', '50');
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES (7, 'Diferimento', '51');
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES (8, 'ICMS cobrado anteriormente por substituição tributária', '60');
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES (9, 'Com redução de base de cálculo e cobrança de ICMS por substituição tributária', '70');
INSERT INTO TBTRIBUTACAO_TIPO (TPT_COD, TPT_DESCRICAO, TPT_SIGLA)
                       VALUES (10, 'Outras', '90');

COMMIT WORK;

CREATE SEQUENCE GEN_GRUPOPRODUTO_COD;

CREATE TRIGGER TG_GRUPOPRODUTO_COD FOR TBGRUPOPROD
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.COD IS NULL) THEN
    NEW.COD = GEN_ID(GEN_GRUPOPRODUTO_COD,1);
END;

/******************************************************************************/
/***               Generated by IBExpert 29/12/2011 13:53:02                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;

/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/

CREATE GENERATOR GEN_SECAOPRODUTO_ID;

CREATE TABLE TBSECAOPROD (
    SCP_COD        SMALLINT NOT NULL,
    SCP_DESCRICAO  VARCHAR(50)
);

/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TBSECAOPROD ADD CONSTRAINT PK_TBSECAOPROD PRIMARY KEY (SCP_COD);

/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/

SET TERM ^ ;

/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/

/* Trigger: TG_SECAOPRODUTO_COD */
CREATE OR ALTER TRIGGER TG_SECAOPRODUTO_COD FOR TBSECAOPROD
ACTIVE BEFORE INSERT POSITION 0
As
Begin
  If (New.Scp_cod Is Null) Then
    New.Scp_cod = Gen_id(Gen_secaoproduto_id,1);
End
^

SET TERM ; ^

/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/

/******************************************************************************/
/***               Generated by IBExpert 29/12/2011 14:14:47                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;

/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/

CREATE GENERATOR GEN_UNIDADEPRODUTO_ID;

CREATE TABLE TBUNIDADEPROD (
    UNP_COD        SMALLINT NOT NULL,
    UNP_DESCRICAO  VARCHAR(50),
    UNP_SIGLA      VARCHAR(5)
);

/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TBUNIDADEPROD ADD CONSTRAINT PK_TBUNIDADEPROD PRIMARY KEY (UNP_COD);

/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/

SET TERM ^ ;

/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/

/* Trigger: TG_UNIDADEPRODUTO_COD */
CREATE OR ALTER TRIGGER TG_UNIDADEPRODUTO_COD FOR TBUNIDADEPROD
ACTIVE BEFORE INSERT POSITION 0
As
Begin
  If (New.Unp_cod Is Null) Then
    New.Unp_cod = Gen_id(Gen_unidadeproduto_id,1);
End
^

SET TERM ; ^

/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/

