CREATE DOMAIN DMN_BIGINT_NN AS BIGINT NOT NULL;

ALTER TABLE TVENDASITENS DROP CONSTRAINT PK_TVENDASITENS;

ALTER TABLE TBVENDAS DROP CONSTRAINT PK_TBVENDAS;

ALTER TABLE TBVENDAS ALTER CODCONTROL TYPE DMN_BIGINT_NN;

alter table TBVENDAS add constraint PK_TBVENDAS primary key (CODCONTROL);

ALTER TABLE TVENDASITENS ALTER CODCONTROL TYPE DMN_BIGINT_NN;

ALTER TABLE TVENDASITENS ADD SEQ SMALLINT NOT NULL;

Update TVENDASITENS Set SEQ = 1;

alter table TVENDASITENS add constraint PK_TVENDASITENS primary key (CODCONTROL,SEQ,CODPROD);

alter table TBVENDAS
add constraint FK_TBVENDAS_EMPRESA
foreign key (CODEMP)
references TBEMPRESA(CNPJ)
on update CASCADE;

alter table TBVENDAS
add constraint FK_TBVENDAS_CLIENTE
foreign key (CODCLI)
references TBCLIENTE(CNPJ)
on update CASCADE;

ALTER TABLE TVENDASITENS DROP CONSTRAINT FK_TVENDASITENS_1;

ALTER TABLE TVENDASITENS DROP CONSTRAINT FK_TVENDASITENS_2;

ALTER TABLE TVENDASITENS DROP CONSTRAINT FK_TVENDASITENS_3;

alter table TVENDASITENS
add constraint FK_TVENDASITENS_PRODUTO
foreign key (CODPROD)
references TBPRODUTO(COD);

alter table TVENDASITENS
add constraint FK_TVENDASITENS_EMPRESA
foreign key (CODEMP)
references TBEMPRESA(CNPJ)
on update CASCADE;

alter table TVENDASITENS
add constraint FK_TVENDASITENS_CLIENTE
foreign key (CODCLI)
references TBCLIENTE(CNPJ)
on update CASCADE;

CREATE SEQUENCE GEN_VENDAS_CONTROLE;

CREATE TRIGGER TG_VENDAS_CONTROLE FOR TBVENDAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODCONTROL IS NULL) THEN
    NEW.CODCONTROL = GEN_ID(GEN_VENDAS_CONTROLE, 1);
END
 
CREATE OR ALTER Trigger Trgbaixaestoqq For Tvendasitens
Inactive After Insert Position 0
AS
begin
  update tbproduto p set qtde = qtde - new.qtde
     where cod=new.codprod;
  insert into tbprodhist values(new.codprod, new.codcontrol,'Venda - Saída',new.dtvenda, 0, new.qtde, new.qtdefinal,'dorivas',new.pfinal);
end




