/******************************************************************************/
/***               Generated by IBExpert 05/01/2012 16:25:18                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_CONDICAOPAGTO_COD;

CREATE TABLE TBCONDICAOPAGTO (
    COND_COD        SMALLINT NOT NULL,
    COND_DESCRICAO  VARCHAR(80),
    COND_PRAZO      DMN_LOGICO /* DMN_LOGICO = SMALLINT DEFAULT 0 NOT NULL CHECK (value between 0 and 1) */,
    COND_PRAZO_01   SMALLINT,
    COND_PRAZO_02   SMALLINT,
    COND_PRAZO_03   SMALLINT,
    COND_PRAZO_04   SMALLINT,
    COND_PRAZO_05   SMALLINT,
    COND_PRAZO_06   SMALLINT,
    COND_PRAZO_07   SMALLINT,
    COND_PRAZO_08   SMALLINT,
    COND_PRAZO_09   SMALLINT,
    COND_PRAZO_10   SMALLINT,
    COND_PRAZO_11   SMALLINT,
    COND_PRAZO_12   SMALLINT
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TBCONDICAOPAGTO ADD CONSTRAINT PK_TBCONDICAOPAGTO PRIMARY KEY (COND_COD);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: TG_CONDICAOPAGTO_COD */
CREATE OR ALTER TRIGGER TG_CONDICAOPAGTO_COD FOR TBCONDICAOPAGTO
ACTIVE BEFORE INSERT POSITION 0
As
Begin
  If (New.Cond_cod Is Null) Then
    New.Cond_cod = Gen_id(Gen_condicaopagto_cod, 1);
End
^


SET TERM ; ^



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


CREATE VIEW VW_CONDICAOPAGTO(
    COND_COD,
    COND_DESCRICAO,
    COND_PRAZO,
    COND_PRAZO_01,
    COND_PRAZO_02,
    COND_PRAZO_03,
    COND_PRAZO_04,
    COND_PRAZO_05,
    COND_PRAZO_06,
    COND_PRAZO_07,
    COND_PRAZO_08,
    COND_PRAZO_09,
    COND_PRAZO_10,
    COND_PRAZO_11,
    COND_PRAZO_12,
    COND_DESCRICAO_FULL)
AS
Select
    c.Cond_cod
  , c.Cond_descricao
  , c.Cond_prazo
  , c.Cond_prazo_01
  , c.Cond_prazo_02
  , c.Cond_prazo_03
  , c.Cond_prazo_04
  , c.Cond_prazo_05
  , c.Cond_prazo_06
  , c.Cond_prazo_07
  , c.Cond_prazo_08
  , c.Cond_prazo_09
  , c.Cond_prazo_10
  , c.Cond_prazo_11
  , c.Cond_prazo_12
  , c.Cond_descricao || ' [' ||
      case when c.Cond_prazo_01 is not Null then c.Cond_prazo_01 else '' end ||
      case when c.Cond_prazo_02 is not Null then ', ' || c.Cond_prazo_02 else '' end ||
      case when c.Cond_prazo_03 is not Null then ', ' || c.Cond_prazo_03 else '' end ||
      case when c.Cond_prazo_04 is not Null then ', ' || c.Cond_prazo_04 else '' end ||
      case when c.Cond_prazo_05 is not Null then ', ' || c.Cond_prazo_05 else '' end ||
      case when c.Cond_prazo_06 is not Null then ', ' || c.Cond_prazo_06 else '' end ||
      case when c.Cond_prazo_07 is not Null then ', ' || c.Cond_prazo_07 else '' end ||
      case when c.Cond_prazo_08 is not Null then ', ' || c.Cond_prazo_08 else '' end ||
      case when c.Cond_prazo_09 is not Null then ', ' || c.Cond_prazo_09 else '' end ||
      case when c.Cond_prazo_10 is not Null then ', ' || c.Cond_prazo_10 else '' end ||
      case when c.Cond_prazo_11 is not Null then ', ' || c.Cond_prazo_11 else '' end ||
      case when c.Cond_prazo_12 is not Null then ', ' || c.Cond_prazo_12 else '' end || ']'
    as Cond_descricao_full
from TBCONDICAOPAGTO c
;

INSERT INTO TBFORMPAGTO (COD, DESCRI, ACRESCIMO)
                 VALUES (1, 'CARTEITA', 0);
INSERT INTO TBFORMPAGTO (COD, DESCRI, ACRESCIMO)
                 VALUES (2, 'CHEQUE', 0);
INSERT INTO TBFORMPAGTO (COD, DESCRI, ACRESCIMO)
                 VALUES (3, 'CARTÃO', 0);
INSERT INTO TBFORMPAGTO (COD, DESCRI, ACRESCIMO)
                 VALUES (4, 'DEPÓSITO', 0);
INSERT INTO TBFORMPAGTO (COD, DESCRI, ACRESCIMO)
                 VALUES (5, 'A PRAZO', 0);

COMMIT WORK;
