CREATE DOMAIN DMN_BIGINT_NN AS BIGINT NOT NULL;

ALTER TABLE TVENDASITENS DROP CONSTRAINT PK_TVENDASITENS;

ALTER TABLE TBVENDAS DROP CONSTRAINT PK_TBVENDAS;

ALTER TABLE TBVENDAS ALTER CODCONTROL TYPE DMN_BIGINT_NN;

alter table TBVENDAS add constraint PK_TBVENDAS primary key (CODCONTROL);

ALTER TABLE TVENDASITENS ALTER CODCONTROL TYPE DMN_BIGINT_NN;

ALTER TABLE TVENDASITENS ADD SEQ SMALLINT NOT NULL;

Update TVENDASITENS Set SEQ = 1;

alter table TVENDASITENS add constraint PK_TVENDASITENS primary key (CODCONTROL,SEQ,CODPROD);

alter table TBVENDAS
add constraint FK_TBVENDAS_EMPRESA
foreign key (CODEMP)
references TBEMPRESA(CNPJ)
on update CASCADE;

alter table TBVENDAS
add constraint FK_TBVENDAS_CLIENTE
foreign key (CODCLI)
references TBCLIENTE(CNPJ)
on update CASCADE;

ALTER TABLE TVENDASITENS DROP CONSTRAINT FK_TVENDASITENS_1;

ALTER TABLE TVENDASITENS DROP CONSTRAINT FK_TVENDASITENS_2;

ALTER TABLE TVENDASITENS DROP CONSTRAINT FK_TVENDASITENS_3;

alter table TVENDASITENS
add constraint FK_TVENDASITENS_PRODUTO
foreign key (CODPROD)
references TBPRODUTO(COD);

alter table TVENDASITENS
add constraint FK_TVENDASITENS_EMPRESA
foreign key (CODEMP)
references TBEMPRESA(CNPJ)
on update CASCADE;

alter table TVENDASITENS
add constraint FK_TVENDASITENS_CLIENTE
foreign key (CODCLI)
references TBCLIENTE(CNPJ)
on update CASCADE;

CREATE SEQUENCE GEN_VENDAS_CONTROLE;

CREATE TRIGGER TG_VENDAS_CONTROLE FOR TBVENDAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.CODCONTROL IS NULL) THEN
    NEW.CODCONTROL = GEN_ID(GEN_VENDAS_CONTROLE, 1);
END
 
CREATE OR ALTER Trigger Trgbaixaestoqq For Tvendasitens
Inactive After Insert Position 0
AS
begin
  update tbproduto p set qtde = qtde - new.qtde
     where cod=new.codprod;
  insert into tbprodhist values(new.codprod, new.codcontrol,'Venda - Saída',new.dtvenda, 0, new.qtde, new.qtdefinal,'dorivas',new.pfinal);
end

CREATE DOMAIN DMN_STATUS AS
SMALLINT
DEFAULT 0
NOT NULL
CHECK (value between 0 and 9);

UPDATE TBVENDAS
SET STATUS = '0';     

update RDB$RELATION_FIELDS set
RDB$FIELD_SOURCE = 'DMN_STATUS',
RDB$COLLATION_ID = -1
where (RDB$FIELD_NAME = 'STATUS') and
(RDB$RELATION_NAME = 'TBVENDAS');

CREATE DOMAIN DMN_VCHAR_04 AS
VARCHAR(4);

ALTER TABLE TBVENDAS
    ADD SERIE DMN_VCHAR_04,
    ADD NFE BIGINT,
    ADD DATAEMISSAO DATE,
    ADD HORAEMISSAO TIME,
    ADD VERIFICADOR_NFE VARCHAR(250),
    ADD XML_NFE BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    ADD VENDEDOR_COD INTEGER,
    ADD USUARIO VARCHAR(50) DEFAULT user,
    ADD FORMAPAGTO_COD SMALLINT,
    ADD CONDICAOPAGTO_COD SMALLINT,
    ADD VENDA_PRAZO DMN_LOGICO,
    ADD PRAZO_01 SMALLINT,
    ADD PRAZO_02 SMALLINT,
    ADD PRAZO_03 SMALLINT,
    ADD PRAZO_04 SMALLINT,
    ADD PRAZO_05 SMALLINT,
    ADD PRAZO_06 SMALLINT,
    ADD PRAZO_07 SMALLINT,
    ADD PRAZO_08 SMALLINT,
    ADD PRAZO_09 SMALLINT,
    ADD PRAZO_10 SMALLINT,
    ADD PRAZO_11 SMALLINT,
    ADD PRAZO_12 SMALLINT;
    
UPDATE TBVENDAS
SET VENDA_PRAZO = 0;     

alter table TBVENDAS
add constraint FK_TBVENDAS_VENDEDOR
foreign key (VENDEDOR_COD)
references TBVENDEDOR(COD);

alter table TBVENDAS
add constraint FK_TBVENDAS_FORMAPGTO
foreign key (FORMAPAGTO_COD)
references TBFORMPAGTO(COD);

alter table TBVENDAS
add constraint FK_TBVENDAS_CONDPGTO
foreign key (CONDICAOPAGTO_COD)
references TBCONDICAOPAGTO(COND_COD);

alter table TBVENDAS
add constraint UNQ_TBVENDAS_NFE
unique (SERIE,NFE);



