


/*------ SYSDBA 01/02/2012 23:13:46 --------*/

CREATE TABLE TBFUNCAO (
    COD SMALLINT NOT NULL,
    FUNCAO VARCHAR(25));
alter table TBFUNCAO
add constraint PK_TBFUNCAO
primary key (COD);
CREATE SEQUENCE GEN_TBFUNCAO_ID;



/*------ SYSDBA 01/02/2012 23:14:00 --------*/

alter table TBFUNCAO
add constraint UNQ1_TBFUNCAO
unique (FUNCAO);



/*------ SYSDBA 01/02/2012 23:14:57 --------*/

ALTER TABLE TBUSERS DROP FUNCAO;



/*------ SYSDBA 01/02/2012 23:15:35 --------*/

update RDB$FIELDS set
RDB$FIELD_LENGTH = 16,
RDB$CHARACTER_LENGTH = 16
where RDB$FIELD_NAME = 'RDB$602'
;



/*------ SYSDBA 01/02/2012 23:16:18 --------*/

ALTER TABLE TBUSERS
    ADD CODFUNCAO SMALLINT NOT NULL;



/*------ SYSDBA 01/02/2012 23:16:31 --------*/

UPDATE TBUSERS
SET CODFUNCAO = 1;



/*------ SYSDBA 01/02/2012 23:24:30 --------*/

alter table TBUSERS
add constraint FK_TBUSERS_1
foreign key (CODFUNCAO)
references TBFUNCAO(COD);



/*------ SYSDBA 04/02/2012 09:19:23 --------*/

ALTER TABLE TBUSERS
    ADD LIMIDESC DECIMAL(2,2);



/*------ SYSDBA 04/02/2012 09:21:04 --------*/

ALTER TABLE TBUSERS ADD IBE$$TEMP_COLUMN
 NUMERIC(1,1) DEFAULT 0.00
;
UPDATE RDB$RELATION_FIELDS F1
SET
F1.RDB$DEFAULT_VALUE  = (SELECT F2.RDB$DEFAULT_VALUE
                         FROM RDB$RELATION_FIELDS F2
                         WHERE (F2.RDB$RELATION_NAME = 'TBUSERS') AND
                               (F2.RDB$FIELD_NAME = 'IBE$$TEMP_COLUMN')),
F1.RDB$DEFAULT_SOURCE = (SELECT F3.RDB$DEFAULT_SOURCE FROM RDB$RELATION_FIELDS F3
                         WHERE (F3.RDB$RELATION_NAME = 'TBUSERS') AND
                               (F3.RDB$FIELD_NAME = 'IBE$$TEMP_COLUMN'))
WHERE (F1.RDB$RELATION_NAME = 'TBUSERS') AND
      (F1.RDB$FIELD_NAME = 'LIMIDESC');
ALTER TABLE TBUSERS DROP IBE$$TEMP_COLUMN;
