ALTER TABLE TBCONTREC
ADD CODBANCO INTEGER;

ALTER TABLE TBCONTREC
ADD NOSSONUMERO VARCHAR(20) CHARACTER SET ISO8859_2 
COLLATE ISO8859_2;

ALTER TABLE TBCONTREC
ADD REMESSA INTEGER;

ALTER TABLE TBCONTREC
ADD VALORSALDO NUMERIC(10,2);

ALTER TABLE TBCONTREC
ADD PERCENTJUROS NUMERIC(5,2);

ALTER TABLE TBCONTREC
ADD PERCENTMULTA NUMERIC(5,2);

ALTER TABLE TBCONTREC
ADD PERCENTDESCONTO NUMERIC(5,2);

ALTER TABLE TBCONTREC
ADD BAIXADO SMALLINT
DEFAULT 0 
NOT NULL;

ALTER TABLE TBCONTREC
ADD ENVIADO SMALLINT
DEFAULT 0 
NOT NULL;

ALTER TABLE TBCONTREC
ADD DATAPROCESSOBOLETO DATE;

CREATE INDEX IDX_TBCONTREC_NOSSONUMERO
ON TBCONTREC (CODBANCO,NOSSONUMERO);

UPDATE TBCONTREC SET BAIXADO = 0;

UPDATE TBCONTREC SET ENVIADO = 0;

Update TBCONTREC set baixado = 1 where dtrec is not null;

Update TBCONTREC set valorsaldo = ( coalesce(valorrec, 0) + coalesce(valormulta, 0) - ( coalesce(valorrec, 0) * coalesce(percentdesconto, 0) / 100 ) ) - coalesce(valorrectot, 0);

