/******************************************************************************/
/***               Generated by IBExpert 16/03/2011 11:09:01                ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE TBBANCO_BOLETO (
    BCO_COD                SMALLINT NOT NULL,
    BCO_CARTEIRA           VARCHAR(10) NOT NULL,
    BCO_NOME               VARCHAR(50),
    BCO_CHAVE              VARCHAR(10),
    BCO_AGENCIA            VARCHAR(10),
    BCO_CC                 VARCHAR(10),
    BCO_NOSSO_NUM_INICIO   VARCHAR(10),
    BCO_NOSSO_NUM_FINAL    VARCHAR(10),
    BCO_NOSSO_NUM_PROXIMO  VARCHAR(10),
    BCO_CONFG_1            VARCHAR(20),
    BCO_CONFG_2            VARCHAR(20),
    BCO_SEQUENCIAL_REM     INTEGER DEFAULT 1 NOT NULL,
    BCO_DIRETORIO_REMESSA  VARCHAR(100),
    BCO_DIRETORIO_RETORNO  VARCHAR(100)
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE TBBANCO_BOLETO ADD CONSTRAINT PK_TBBANCO_BOLETO PRIMARY KEY (BCO_COD);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON TBBANCO_BOLETO TO PUBLIC;

/******************************************************************************/
/***                               Datas                                    ***/
/******************************************************************************/

INSERT INTO TBBANCO_BOLETO (BCO_COD, BCO_CARTEIRA, BCO_NOME, BCO_CHAVE, BCO_AGENCIA, BCO_CC, BCO_NOSSO_NUM_INICIO, BCO_NOSSO_NUM_FINAL, BCO_NOSSO_NUM_PROXIMO, BCO_CONFG_1, BCO_CONFG_2, BCO_SEQUENCIAL_REM, BCO_DIRETORIO_REMESSA, BCO_DIRETORIO_RETORNO)
                    VALUES (1, '11', 'BANCO DO BRASIL S.A', '000005711', '0174-9', '00000571-1', '000001', '999999', '30', '0', '0', 4, 'C:\Projects\Dorivaldo\Boleto\Retorno\', 'C:\Projects\Dorivaldo\Boleto\Retorno\');
INSERT INTO TBBANCO_BOLETO (BCO_COD, BCO_CARTEIRA, BCO_NOME, BCO_CHAVE, BCO_AGENCIA, BCO_CC, BCO_NOSSO_NUM_INICIO, BCO_NOSSO_NUM_FINAL, BCO_NOSSO_NUM_PROXIMO, BCO_CONFG_1, BCO_CONFG_2, BCO_SEQUENCIAL_REM, BCO_DIRETORIO_REMESSA, BCO_DIRETORIO_RETORNO)
                    VALUES (341, '115', 'BANCO ITAU S.A.', '000044977', '07218', '00004497-7', '000001', '999999', '13', '0', '0', 4, 'C:\Projects\Dorivaldo\Boleto\Retorno\', 'C:\Projects\Dorivaldo\Boleto\Retorno\');

COMMIT WORK;